### ISSUE TITLE
[1][55][3]Issue in Sister Project, Regex needs help for FastColoredTextBox

### ISSUE THREAD

**Issue by brandoncomputer** [brandoncomputer/vds#97]
I've got everything solved except multiline regex for comments.

If someone is a Regex expert, please post a comment here or clone https://github.com/brandoncomputer/FastColoredTextBox

            CSharpCommentRegex1 = new Regex(@"#.*$", RegexOptions.Multiline | RegexCompiledOption);
            CSharpCommentRegex2 = new Regex(pattern: @"(/<\#[\s\S]*?\#\>/)|([^:]|^)\#.*$", options: RegexOptions.Multiline | RegexCompiledOption);
            CSharpCommentRegex3 = new Regex(@"(/\#.*?\#/)|(.*\#/)",
                                            RegexOptions.Singleline | RegexOptions.RightToLeft | RegexCompiledOption);
            CSharpCommentRegex4 = new Regex(@"<\#.*$", RegexOptions.Multiline | RegexCompiledOption);
            CSharpCommentRegex5 = new Regex(@"rem.*$", RegexOptions.Multiline | RegexCompiledOption);
            CSharpNumberRegex = new Regex(@"\b\d+[\.]?\d*([eE]\-?\d+)?[lLdDfF]?\b|\b0x[a-fA-F\d]+\b",
                                          RegexCompiledOption);
            CSharpAttributeRegex = new Regex(@"^\s*(?<range>\[.+?\])\s*$", RegexOptions.Multiline | RegexCompiledOption);

            CSharpClassNameRegex = new Regex(@"\$(?<range>\w+)", RegexCompiledOption);
           
            CSharpClassNameRegex1 = new Regex(@"\b(function)\s+(?<range>\w+?)\b", RegexCompiledOption);

**Comment by AhmadCracks** [comment]
I like your post. It's informative and helpful for us. please keep it up.
Thanku.
<a href="https://ahmadcracks.com/">Serial Key Download</a>

**Comment by brandoncomputer** [comment]
Closed per project restructure
